### ISSUE TITLE
Wanna ask some questions about metaSense

### ISSUE THREAD

**Issue by Ma-Zijing** [TaesikGong/MetaSense_public#1]
Hi TaesikGong, I try to reproduce metaSense with your code, but there are some questions I do not figure out.
1. When I reproduce metaSense, python raises an error of 'RuntimeError: CUDA error: out of memory'. The dataset is hhar_scaled. It seems the reason is that the size of csv file is too large to load to cuda. How do you load this csv file in metaSense to avoid out of memory?
2. I want to ask the difference of parameter '--src' when it is 'all' and 'rest' respectively?
3. Can you give some examples of parameter '--tgt'? Since it has no defaults or examples in the code.
I am looking forward to you replies. Thanks!

**Comment by TaesikGong** [comment]
Hi bigMaxM!
First of all, thank you for your interest in our project.
1. I think you can just reduce the batch size to prevent the out-of-memory error. FYI, we used GPUs with 12GB RAM each.
2. 'all' was originally to investigate the effect of having some target data in the source domain, but it is deprecated. So please ignore it.
3. You can refer to run.sh which lists the target domains for each dataset.
Thank you and feel free to ask further questions!
